mailbot: fix kbuild reactions in BPF
The current code doesn't work we get:

   ERROR: too many actions for un-authorized user
 Actions:
   pw-bot: changes-requested
   pw-bot: changes-requested

We need to flush the actions.

Signed-off-by: Jakub Kicinski <kuba@kernel.org>