contest: vm: add retry id to the crash path
We need to make the crash path unique. Otherwise on retry:

  FileExistsError: [Errno 17] File exists: '...outputs-5/results/426501/vm-crashed-0'

Signed-off-by: Jakub Kicinski <kuba@kernel.org>