contest: retry later when unable to load input files
The contest service was unable to load the 'branch_info' input file
twice yesterday. Probably because it was being updated:

  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Catch the error, and retry later.

Signed-off-by: Matthieu Baerts <matttbe@kernel.org>