pw: retry on 404 errors
This is a temp fix while Lore is being used to retrieve patches.

Because PW and Lore are two async services now used to get info about
patches, it is possible one is updated after the other. This is
problematic if Lore is updated after, and this already happened:

  pw.patchwork.PatchworkFetchException: ('https://lore.kernel.org/all/20260908132926.68976-6-luka.gejak%40linux.dev/raw', <Response [404]>)

The URL is now valid, but it wasn't at that time.

Retrying is the solution, but it feels like when PW is fixed, it would
be better to use it to download patches as well instead of relying on
different services that can have different issues.

An alternative is to use two different sessions, but if all of this is
linked to a temp workaround, no need to bother.

Signed-off-by: Matthieu Baerts <matttbe@kernel.org>