brancher: explicitly create a branch
Strangely, the brancher service wasn't able to push a new branch
recently:

  $ git push brancher HEAD:net-next-2026-10-01--03-00
  error: The destination you provided is not a full refname (i.e.,
  starting with "refs/"). We tried to guess what you meant by:

  - Looking for a ref that matches 'net-next-2026-10-01--03-00' on the
    remote side.
  - Checking if the <src> being pushed ('HEAD')
    is a ref in "refs/{heads,tags}/". If so we add a corresponding
    refs/{heads,tags}/ prefix on the remote side.

  Neither worked, so we gave up. You must fully qualify the ref.

The error makes sense, but it is strange because it always worked
before.

Explicitly create a branch by passing 'refs/heads/'.

Signed-off-by: Matthieu Baerts <matttbe@kernel.org>