tests: kdoc: handle missing files
When files are added or removed kdoc script complains:

  Error: Cannot open file ...

ignore those lines.

Signed-off-by: Jakub Kicinski <kuba@kernel.org>